// The fan's external CSS keyframes and geometric acceptance checks share one model.
import {mkdtemp, readFile, rm, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import ts from 'typescript';

const directory = await mkdtemp(join(tmpdir(), 'diedu-fan-css-'));
try {
  const source = await readFile(new URL('../src/core/gallery-motion.ts', import.meta.url), 'utf8');
  const result = ts.transpileModule(source, {compilerOptions: {target: ts.ScriptTarget.ES2022, module: ts.ModuleKind.ES2022}});
  const path = join(directory, 'gallery-motion.mjs');
  await writeFile(path, result.outputText);
  const {GALLERY_FAN_CONTACT_LIFT, GALLERY_FAN_FRAME_RATE, galleryOrbitPose} = await import(pathToFileURL(path).href);
  const number = value => String(Number(value.toFixed(7)));
  const scale = value => `calc(var(--gallery-size)*${number(value)})`;
  const frameCount = GALLERY_FAN_FRAME_RATE * 8;
  const frames = Array.from({length: frameCount + 1}, (_, index) => {
    const pose = galleryOrbitPose('fan', index / GALLERY_FAN_FRAME_RATE - 4);
    return `  ${number(index * 100 / frameCount)}%{transform:translate(-50%,-50%) translate3d(${scale(pose.x)},${scale(pose.y)},${scale(pose.z)}) rotateX(${number(pose.rotateX)}deg) rotateY(${number(pose.rotateY)}deg) rotateZ(${number(pose.rotateZ)}deg) scale(${number(pose.scale)});opacity:${number(pose.opacity)}}`;
  });
  await writeFile(new URL('../src/styles/gallery-fan.css', import.meta.url), [
    '/* Generated by web/scripts/gallery-fan.mjs from core/gallery-motion.ts. */',
    '/* A broad rigid-case peel keeps the face legible, with shallow pitch and depth clearance. */',
    `.gallery-orbit.gallery-stage--fan{--case-contact-lift:${number(GALLERY_FAN_CONTACT_LIFT)}px}`,
    '.gallery-orbit.gallery-stage--fan .gallery-orbit-card{animation-name:gallery-orbit-fan;z-index:4}',
    ...Array.from({length: 9}, (_, index) => `.gallery-orbit.gallery-stage--fan .gallery-orbit-card[data-fan-layer="${index + 1}"]{z-index:${(index + 1) * 2}}`),
    '@keyframes gallery-orbit-fan{', ...frames, '}', '',
  ].join('\n'));
} finally {await rm(directory, {recursive: true, force: true});}
